### ISSUE TITLE
Context menu option no longer showing up

### ISSUE THREAD

**Issue by raidcookie** [NightmareXIV/XIVInstantMessenger#19]
After the most recent update, the "Messenger" option in the character context menu does not show up anymore, despite being ticked in the plugin options.

![image](https://github.com/NightmareXIV/XIVInstantMessenger/assets/5206862/7fbb5813-ae68-427f-818d-ef76c6e496e1)

**Comment by guppyfaced** [comment]
saaaaame

**Comment by Limiana** [comment]
I will deal with this issue within next couple days

**Comment by Limiana** [comment]
Fixed, update will be published shortly
