### ISSUE TITLE
Menus Become Transparent

### ISSUE THREAD

**Issue by babieuwu** [NightmareXIV/XIVInstantMessenger#20]
When I click out of a chat window, all of my modded menus become transparent and I can barely see anything, and this only became an issue due to the most recent update. 

![image](https://github.com/NightmareXIV/XIVInstantMessenger/assets/77366256/0e96b12a-0b63-4fcc-818a-3a6f7c8889fa)

**Comment by Limiana** [comment]
Fixed, update will be released shortly
