### ISSUE TITLE
Auto-translate feature doesn't appear

### ISSUE THREAD

**Issue by MNGOwO** [NightmareXIV/XIVInstantMessenger#21]
Upon hitting Tab to prompt the auto-translate to show up nothing happens. 
I'm not sure if this ever was a feature but if I recall correctly XIVInstantMessenger did have the ability to use AutoTranslate before, and no longer does.  

(If this was never a feature, if you could please direct me to a place to make suggestions I would gladly add this to the list.)

**Comment by Limiana** [comment]
Hello!
Unfortunately, there is no support for auto-translate feature. I can't promise I can add it before a major update as well unfortunately due to low amount of time right now and this feature is complicated and would take a lot of time to implement

**Comment by Limiana** [comment]
For now I'll mark it as out of scope as it seems like adding it is a very significant effort and there isn't that much use cases
