### ISSUE TITLE
Have to use commands to type if Chat2 is installed alongside XIM

### ISSUE THREAD

**Issue by n1-d** [NightmareXIV/XIVInstantMessenger#24]
XIVIM doesn't seem to know how to handle chat channels with Chat2 installed. Refuses to swap them, so typing in any channels on the popup requires you to go and use commands.

Errors out like this. 

[Image](https://i.imgur.com/XyvUeSx.png)

**Comment by Limiana** [comment]
Hello! Thanks for your report, I will check it

**Comment by Limiana** [comment]
Shouldn't be an issue anymore
