### ISSUE TITLE
[Feature Request] process Emote "channel"

### ISSUE THREAD

**Issue by icy-** [NightmareXIV/XIVInstantMessenger#26]
Hi, recently started using xim, would be great if Emotes could be processed -- so the text from /em

It's not a Generic channel, I know, but could really help quality of life to save/share the chat of a roleplaying session! (another checkbox or so)

thanks!

**Comment by icy-** [comment]
looking a little closer, I think a checkbox to process  `XivChatType.CustomEmote`  could do the trick

**Comment by icy-** [comment]
Hi, I just remembered this one again after having a chat with a friend!  Any luck with this one, or is it too different from the other established logged channels?

**Comment by Limiana** [comment]
Hello! Apologies, I didn't got much time to work on plugins lately, but I will be updating it to include this and other features soon

**Comment by icy-** [comment]
No worries, take your time~

**Comment by Limiana** [comment]
been a while, but this is now implemented in 1.4.0.0
