### ISSUE TITLE
Logging History does not save first incoming tell of conversations

### ISSUE THREAD

**Issue by noelneedsanap** [NightmareXIV/XIVInstantMessenger#27]
When I have used the plugin, the first tell from someone is not there when i retrieve the previous DMs from the user list. For example, FC invites that I have replied to will save my reply (and subsequent messages) but not the original message.

I'm not sure if a log will be useful but here is a log and picture of received FC invite and conversation where the initial FC invite is missing:

[Debug] Tab systems: 
[Information] Loading chats from files
[Debug] Sender is _Sender Name_
[Debug] Have read line: [2023.08.26 16:10:14 -05:00] From _My Name_: Hi, I'll consider it! Most of the FC invites I've gotten haven't messaged me about it. I'm not so great with people though so I'm not sure lol
[Debug] Parsed line: 0:[2023.08.26 16:10:14 -05:00] From _My Name_: Hi, I'll consider it! Most of the FC invites I've gotten haven't messaged me about it. I'm not so great with people though so I'm not sure lol
1:2023.08.26 16:10:14 -05:00
2:_My Name_
3:_World_
4:Hi, I'll consider it! Most of the FC invites I've gotten haven't messaged me about it. I'm not so great with people though so I'm not sure lol
[Debug] name: _My Name_, subject: _Sender Name_
[Debug] Have read line: [2023.08.26 16:11:16 -05:00] From _Sender Name_: again, no presure and its totally up to you. We'd love to have you, I promise we aren't scary lol, we're a community of friends who love to help eachother out
[Debug] Parsed line: 0:[2023.08.26 16:11:16 -05:00] From _Sender Name_: again, no presure and its totally up to you. We'd love to have you, I promise we aren't scary lol, we're a community of friends who love to help eachother out
1:2023.08.26 16:11:16 -05:00
2:_Sender Name_
3:_World_`
4:again, no presure and its totally up to you. We'd love to have you, I promise we aren't scary lol, we're a community of friends who love to help eachother out
[Debug] name: _Sender Name_, subject: _Sender Name_
[Debug] Have read line: 
[Debug] Player _Other Player_ CID=004000174C34CF33

![image](https://github.com/NightmareXIV/XIVInstantMessenger/assets/47755760/e489bb0b-d6bb-4840-9079-423a23bd9fc1)

**Comment by Limiana** [comment]
Resolved in testing version
