### ISSUE TITLE
[Feature Request] Log per character

### ISSUE THREAD

**Issue by Sohtoren** [NightmareXIV/XIVInstantMessenger#28]
Hello,
First thanks for that plugin, tells are so much nicer with it.

As an avid RPer having multiple characters, it would be nice if logs were dedicated per character so logs of another wouldn't be retrieve for the same person and put in a separate sub-folder (perhaps something like Firstname_Lastname_Realm?)  so it's easier to retrieve them.
Currently if I talk to the same person with two different character, the same history is loaded in the window and it can be a bit confusing

**Comment by Deckerz** [comment]
this would be really nice, do you accept PRs for this @Limiana ? or is it in the works?

**Comment by Limiana** [comment]
Added in testing version
