### ISSUE TITLE
Changing words in chat

### ISSUE THREAD

**Issue by Lucina2010** [NightmareXIV/XIVInstantMessenger#30]
Sometimes the chat will completely change What I or others are saying to completely random things, like changing my character's name "L'ucina" to "The kitchen"
![image](https://github.com/NightmareXIV/XIVInstantMessenger/assets/147665254/73ce82e5-3904-4a76-a8e2-52330c139a91)
![image](https://github.com/NightmareXIV/XIVInstantMessenger/assets/147665254/5eaf7cff-da97-4d57-adb8-1aa6c1c97c11)

**Comment by Limiana** [comment]
Hello. Do you possibly have translate feature enabled?
