### ISSUE TITLE
Messages not showing in certain situations

### ISSUE THREAD

**Issue by Lockehart** [NightmareXIV/XIVInstantMessenger#33]
I've noticed when responding to a tell with the same phrase as the person sends you, your message won't show at all.  Example if a person says "heya" and you respond with an exact "heya" it will not show.  Might be a spam filter of some sort going too hard?  Dunno, I'm no expert.  Just reporting it here xD

**Comment by Limiana** [comment]
Hello! Are you using TidyChat maybe?
