### ISSUE TITLE
Emote channel tracking implemented in 1.4.0 release, but not available?

### ISSUE THREAD

**Issue by Counterpoint-Storm** [NightmareXIV/XIVInstantMessenger#35]
I read that emote channel tracking integration was included in the 1.4.0 update, however I've been unable to locate it in the plugin itself. Was the feature pushed back, or yanked for some reason?

**Comment by Limiana** [comment]
Hello! You can activate it in "Generic channels" tab

**Comment by Counterpoint-Storm** [comment]
I thought as much too, and I appreciate your reply, however after looking high and low I see no sign of it. I have my plugin updated through dalamud to the point where it says no updates are available, which leaves me unsure of how to proceed.
![Generic Channels](https://github.com/NightmareXIV/XIVInstantMessenger/assets/135520914/9d422e5b-8f3d-4c73-b157-94ddfd611fb1)

**Comment by Limiana** [comment]
You may need to enable testing version by right clicking the plugin in the installer. Might have to enable testing versions all together in `/xlsettings` - experimental first

**Comment by Counterpoint-Storm** [comment]
This did in fact solve my problem, I mistakenly thought it was out of testing. Thank you.

**Comment by icy-** [comment]
Hi, I too was on stable, and for the first time right-clicked on XIM in /xlplugins and had it find testing version.  An odd thing I see is the default font is different?!  I can't make it go back to the old default, if you can help somehow.  I tried different variations of JP Inconsolata, and it ends up being close but bolder ^_^
![xim_testing_font_small](https://github.com/NightmareXIV/XIVInstantMessenger/assets/236808/e2ed6870-cf0b-4cce-a70e-afcb8056dd9b)

**Comment by Counterpoint-Storm** [comment]
I encountered this initially as well, and I might suggest trying Game:Axis font? It looks close enough to what it was that I was used to it within a few minutes. You can try playing around with the font size too, I bumped mine up slightly to 14pt
