### ISSUE TITLE
Pressing the "Open adventurer plate" button on a chat window opens incorrect player's plate

### ISSUE THREAD

**Issue by Nysterian** [NightmareXIV/XIVInstantMessenger#36]
It's happened to me multiple times, I'm assuming that it has something to do with whether or not the person that I'm talking with is close to me or not, but most of the time that I press the "Open adventurer plate" button, the adventurer plate of a completely different person, often someone that I've never even seen, gets opened instead.

**Comment by Limiana** [comment]
This should be fixed, please reopen if still happens
