### ISSUE TITLE
[Bug] Replying in an open window after getting a GM DM will not send to correct user

### ISSUE THREAD

**Issue by Glorou** [NightmareXIV/XIVInstantMessenger#39]
I went AFK for a bit when a GM messaged me, and I had a window open with a chat with my friend, when I tried to reply to the friend it would instead send to the GM, I had to manually go and /tell them after the failed send, and reload the window to be able to use it properly
![image](https://github.com/NightmareXIV/XIVInstantMessenger/assets/93338547/e74359f5-382f-4d1f-a554-5a4eb5f34179)

**Comment by Limiana** [comment]
This should be resolved, otherwise please reopen this ticket.
Hopefully, you won't get a chance to test it though.
