### ISSUE TITLE
Update pls :D

### ISSUE THREAD

**Issue by Gitterzwerg** [NightmareXIV/XIVInstantMessenger#40]
Needs update for current patch pls :D

**Comment by Limiana** [comment]
> Needs update for current patch pls :D

Dalamud repo temporarily does not accepts plugin updates. If you would like, you can install and use it manually for now, I've uploaded it to releases: https://github.com/NightmareXIV/XIVInstantMessenger/releases

**Comment by Loucka88** [comment]
> > Needs update for current patch pls :D
> 
> Dalamud repo temporarily does not accepts plugin updates. If you would like, you can install and use it manually for now, I've uploaded it to releases: https://github.com/NightmareXIV/XIVInstantMessenger/releases

Its back up again!, would be great if you could update it!
