### ISSUE TITLE
Replyfunktion not working.

### ISSUE THREAD

**Issue by DevilsCreed** [NightmareXIV/XIVInstantMessenger#41]
Found a bug with the replyfunktion. While tryn to use /r it opens a sencond window withc only shows the written message while the replyer opens the first window. Will include screens to get a better gist of what i mean.

![Screenshot 2024-07-07 110811](https://github.com/NightmareXIV/XIVInstantMessenger/assets/91599734/afaffed5-7918-4857-8887-1daad5f2a0f9)

**Comment by DevilsCreed** [comment]
Sorry for the late reply. I'll try to disable chat2 later and see if i can reproduce the error again. If so i'll post it with a screenshot again.

**Comment by Limiana** [comment]
To resolve this issue, Chat2 has to be updated
Unfortunately, may take some time as official repo submissions are temporarily disabled

**Comment by DevilsCreed** [comment]
Ok i've tried it out without Chat2 enabled - It is a problem with Chat2. Thank you for your time and keep up the good work ;)
