### ISSUE TITLE
[Feature Request ?] Option to disable transparency change on hover

### ISSUE THREAD

**Issue by akio4800** [NightmareXIV/XIVInstantMessenger#42]
setting to disable change of transparency on hover
it should only change transparency when actively clicked away

**Comment by akio4800** [comment]
![image](https://github.com/NightmareXIV/XIVInstantMessenger/assets/1228293/8e473836-e3d5-431d-996d-41e089f23a31)
(add option that it only changes on focus events)

**Comment by Limiana** [comment]
added in next version

**Comment by akio4800** [comment]
thank you
