### ISSUE TITLE
Text wrapping acting weird with long urls

### ISSUE THREAD

**Issue by AsunaTsuki** [NightmareXIV/XIVInstantMessenger#44]
If you send a long link for example a discord image link it will wrap with a ton of blank space between the parts of the url as seen here
![image](https://github.com/user-attachments/assets/34419d38-c2f1-4ac5-ac5f-d0d5db975339)

If you make the window narrower or wider, the space between the parts increases/decreases

**Comment by Limiana** [comment]
Fixed in upcoming version
