### ISSUE TITLE
sending a tell causes other resulting penumbra windows to break (text changes color + top bar glows yellow)

### ISSUE THREAD

**Issue by dumbusernameidk** [NightmareXIV/XIVInstantMessenger#45]
I'm not sure how this happened even or what steps to recreate it are but the second i send a /tell to someone the window breaks and it doesn't even display any text. I also see every other GUI from dalamud break by having the text turn to a color that would've been from the /tell window and the tops glow and flash yellow.  I assume this is from a recent update because it did not do this yesterday or the day before. Any idea?

**Comment by Limiana** [comment]
Hey, do you have a screenshot or/and log?

**Comment by dumbusernameidk** [comment]
I can show screenshots but idk about logs? How would i obtain those? like here's the obvious before https://imgur.com/a/6guPDRt
and here's after i get a msg
https://imgur.com/a/1EGABxT

**Comment by johnnylogen** [comment]
hi, happens to me too

**Comment by Limiana** [comment]
> hi, happens to me too. seems to be a particular persons chatlog or whatever im not sure, since all others seem to work fine (?) but whenever i try to DM that person the text color changes and the chat window for that particular person breaks

once this https://github.com/goatcorp/DalamudPluginsD17/pull/4024 pull request is merged, please update and see if that resolves the issue
or you could grab the version from here https://github.com/goatcorp/DalamudPluginsD17/actions/runs/9961092706 install it manually and see if this resolves your issue

**Comment by johnnylogen** [comment]
seems to have fixed it! thank you
