### ISSUE TITLE
[Bug] Sometimes tells are getting sent to the wrong person

### ISSUE THREAD

**Issue by CharlieDelune** [NightmareXIV/XIVInstantMessenger#49]
I had a XIV Instant Messenger window open with someone ("A"). We had been chatting back and forth for a bit.

A queued and got put into a duty, but I didn't realize it. I sent them a message, in **their** instant messenger window. When I hit enter, a **new** instant messenger window opened with **someone else** ("B") and the message went to THEM.

At first I thought it was just a visual bug, but B then responded to the message.

I switched back over to A's instant message window and sent them another message, and it popped up over in B's messenger window, and they responded to that one too.

I'm sure you can see the potential issues here, lol.

**Comment by CharlieDelune** [comment]
Further investigation, I sent another tell to another person ("C").

Then I went back to A's messenger window and sent them another tell. This time I correctly got the "Unable to send /tell. Recipient is in a restricted area." message.

**Comment by Limiana** [comment]
Hello, could you please recreate the issue and me the log from `/xim` - log tab?

**Comment by CharlieDelune** [comment]
```
[Debug@8/9/2024 10:30:50 PM -04:00] Registering ProperOnLogin Available event's framework update
[Debug@8/9/2024 10:30:50 PM -04:00] Firing ProperOnLogin Available event and unregistering framework update
[Verbose@8/9/2024 10:31:59 PM -04:00] New Content ID for Rhea Jakkya@Balmung: 004000174C34960B
[Verbose@8/9/2024 10:35:49 PM -04:00] New Content ID for Bur Loire@Balmung: 004000174BC5A649
[Verbose@8/9/2024 10:40:26 PM -04:00] New Content ID for Clairette Summers@Balmung: 004000174C27F834
[Debug@8/9/2024 10:55:07 PM -04:00] Window Clairette Summers@Balmung just opened
[Verbose@8/9/2024 10:55:22 PM -04:00] Begin send message to Clairette Summers@Balmung False: [message contents redacted]
[Verbose@8/9/2024 10:55:22 PM -04:00] Sending via reply: /r [message contents redacted]
[Verbose@8/9/2024 10:55:22 PM -04:00] Sender is M'lila Tia
[Verbose@8/9/2024 10:55:22 PM -04:00] 0 threads running, 0 are busy, requested 1 threads, Creating new thread to deal with tasks...
[Verbose@8/9/2024 10:55:22 PM -04:00] Message parts: 
- [message contents redacted]
[Verbose@8/9/2024 10:55:22 PM -04:00] Parsed line: 0:[2024.08.04 16:18:53 -04:00] From M'lila Tia@Balmung: B] thanks!!
1:2024.08.04 16:18:53 -04:00
2:M'lila Tia
3:Balmung
4:B] thanks!!
[Verbose@8/9/2024 10:55:22 PM -04:00] Have read line: 
[Verbose@8/9/2024 10:55:22 PM -04:00] Parsed line: 0:[2024.08.04 15:56:48 -04:00] From Galvjn Djt-setlas@Balmung: 10/10 glam tbh
1:2024.08.04 15:56:48 -04:00
2:Galvjn Djt-setlas
3:Balmung
4:10/10 glam tbh
[Debug@8/9/2024 10:55:22 PM -04:00] Waiting for log to be loaded first...
[Verbose@8/9/2024 10:55:22 PM -04:00] Message parts: 
- B] thanks!!
[Verbose@8/9/2024 10:55:22 PM -04:00] Message parts: 
- 10/10 glam tbh
[Debug@8/9/2024 10:55:22 PM -04:00] name: M'lila Tia@Balmung, subject: M'lila Tia@Balmung
[Verbose@8/9/2024 10:55:22 PM -04:00] Have read line: [2024.08.04 16:18:53 -04:00] From M'lila Tia@Balmung: B] thanks!!
[Verbose@8/9/2024 10:55:22 PM -04:00] Thread 26D613FA begins!
[Verbose@8/9/2024 10:55:22 PM -04:00] Have read line: [2024.08.04 15:56:48 -04:00] From Galvjn Djt-setlas@Balmung: 10/10 glam tbh
[Debug@8/9/2024 10:55:22 PM -04:00] name: Galvjn Djt-setlas@Balmung, subject: M'lila Tia@Balmung
[Debug@8/9/2024 10:55:22 PM -04:00] Window M'lila Tia@Balmung just opened
[Verbose@8/9/2024 10:55:29 PM -04:00] Begin send message to Clairette Summers@Balmung False: wait
[Verbose@8/9/2024 10:55:29 PM -04:00] Sending via reply: /r wait
[Verbose@8/9/2024 10:55:29 PM -04:00] Sender is M'lila Tia
[Verbose@8/9/2024 10:55:29 PM -04:00] Message parts: 
- wait
[Verbose@8/9/2024 10:55:32 PM -04:00] Thread 26D613FA ends!
[Information@8/9/2024 10:56:53 PM -04:00] Loading chats from files
[Verbose@8/9/2024 10:56:53 PM -04:00] 0 threads running, 0 are busy, requested 1 threads, Creating new thread to deal with tasks...
[Verbose@8/9/2024 10:56:53 PM -04:00] Thread 1ED4A5E3 begins!
[Verbose@8/9/2024 10:56:56 PM -04:00] Sender is M'lila Tia
[Debug@8/9/2024 10:56:56 PM -04:00] Window M'lila Tia@Balmung just opened
[Verbose@8/9/2024 10:57:00 PM -04:00] Sender is M'lila Tia
[Verbose@8/9/2024 10:57:00 PM -04:00] Message parts: 
- wot
[Debug@8/9/2024 10:57:00 PM -04:00] Window M'lila Tia@Balmung just opened
[Verbose@8/9/2024 10:57:03 PM -04:00] Thread 1ED4A5E3 ends!
[Verbose@8/9/2024 10:57:17 PM -04:00] Begin send message to M'lila Tia@Balmung False: Yeah I have no idea. I sent a message to someone else, and it popped up as having sent a message to you
[Verbose@8/9/2024 10:57:17 PM -04:00] Sending via reply: /r Yeah I have no idea. I sent a message to someone else, and it popped up as having sent a message to you
[Verbose@8/9/2024 10:57:17 PM -04:00] Sender is M'lila Tia
[Verbose@8/9/2024 10:57:17 PM -04:00] Message parts: 
- Yeah I have no idea. I sent a message to someone else, and it popped up as having sent a message to you
[Verbose@8/9/2024 10:57:28 PM -04:00] Sender is M'lila Tia
[Verbose@8/9/2024 10:57:28 PM -04:00] Message parts: 
- ...wot.
```


This part is of particular interest:

```[Debug@8/9/2024 10:55:07 PM -04:00] Window Clairette Summers@Balmung just opened
[Verbose@8/9/2024 10:55:22 PM -04:00] Begin send message to Clairette Summers@Balmung False: [message contents redacted]
[Verbose@8/9/2024 10:55:22 PM -04:00] Sending via reply: /r [message contents redacted]
[Verbose@8/9/2024 10:55:22 PM -04:00] Sender is M'lila Tia```

That's the part where I send a person a message and then it decides I've sent it to someone else.

**Comment by Limiana** [comment]
Okay, could you additionally send me `%appdata%\XIVLauncher\dalamud.log` file? You can remove your names/messages/etc other private info

**Comment by CharlieDelune** [comment]
Then I sent a tell to someone else, and tried to send a tell to the first person again, and got the correct warning message.
```
[Verbose@8/9/2024 11:05:03 PM -04:00] Sender is Rhea Jakkya
[Verbose@8/9/2024 11:05:03 PM -04:00] 0 threads running, 0 are busy, requested 1 threads, Creating new thread to deal with tasks...
[Verbose@8/9/2024 11:05:03 PM -04:00] Message parts: 
- Ignore this tell
[Debug@8/9/2024 11:05:03 PM -04:00] Window Rhea Jakkya@Balmung just opened
[Verbose@8/9/2024 11:05:03 PM -04:00] Have read line: 
[Verbose@8/9/2024 11:05:03 PM -04:00] Thread 05528818 begins!
[Debug@8/9/2024 11:05:03 PM -04:00] Waiting for log to be loaded first...
[Verbose@8/9/2024 11:05:10 PM -04:00] Sender is Clairette Summers
[Verbose@8/9/2024 11:05:10 PM -04:00] Message parts: 
- Test
[Debug@8/9/2024 11:05:10 PM -04:00] Window Clairette Summers@Balmung just opened
[Verbose@8/9/2024 11:05:11 PM -04:00] Message parts: 
- Unable to send /tell. Recipient is in a restricted area.
[Verbose@8/9/2024 11:05:13 PM -04:00] Thread 05528818 ends!
```

**Comment by CharlieDelune** [comment]
[censored.log](https://github.com/user-attachments/files/16568358/censored.log)
[censored_no_disposing.log](https://github.com/user-attachments/files/16568359/censored_no_disposing.log)
I'm including the raw log from right before I sent the message that was broken until right after I sent the message that properly gave me the warning that the person was in a restricted area.
I also attached a version that is exactly the same but has thousands of lines of "Disposing 1 texture" removed because it might be a lot easier to read that way.

**Comment by Limiana** [comment]
I suspect there is an interference from some other plugin, because the only way that last received message is changed is when you get incoming DM from said user. Either some plugin hides message from XIM or modifies reply channel.
I need log's beginning to see which plugins you have installed.
I have an update pending and in meantime I disabled sending messages via reply channel until I figure out what's causing this issue, will break replying to PF messages but whatever. Hopefully update will be merged some time soon.

**Comment by CharlieDelune** [comment]
[censored_no_disposing.log](https://github.com/user-attachments/files/16568378/censored_no_disposing.log)
[censored.log](https://github.com/user-attachments/files/16568379/censored.log)
I'm including the raw log from right before I sent the message that was broken until right after I sent the message that properly gave me the warning that the person was in a restricted area.
I also attached a version that is exactly the same but has thousands of lines of "Disposing 1 texture" removed because it might be a lot easier to read that way.

**Comment by Limiana** [comment]
Please send me the log where I can see your installed plugins, easiest would be to restart the game if that info got overwritten
I'll see this issue further tomorrow, I'm going to bed now
If you want, you can grab a build from here https://github.com/goatcorp/DalamudPluginsD17/actions/runs/10328772335 and manually install it (go to `%appdata%\XIVLauncher\installedPlugins\Messenger\1.4.0.7\` folder and replace it's content with content from zip file while plugin is disabled) - that build has sending via reply function disabled

**Comment by CharlieDelune** [comment]
> Please send me the log where I can see your installed plugins
[initial_load.log](https://github.com/user-attachments/files/16568445/initial_load.log)
I've got you the entire beginning of the file all the way up until the load finishes because I don't know what's relevant. After this point it's several minutes of "Discarded 1 texture."

> the only way that last received message is changed is when you get incoming DM from said user.

I have not talked to the person who the reply went to in 5 days. I don't even know that person. I sent them one tell, they sent me one back, that was it, 5 days ago. The person who I *tried* to message was someone who I had literally been having a conversation with only moments prior.

> I suspect there is an interference from some other plugin. Either some plugin hides message from XIM or modifies reply channel.

Could be, I wouldn't know. I don't *think* I have any other chat or tell related plugins, but I guess I don't know the underlying code for all these plugins.

**Comment by Limiana** [comment]
By the way this issue should be fixed quite a bit of time ago. Is it?

**Comment by CharlieDelune** [comment]
> By the way this issue should be fixed quite a bit of time ago. Is it?

I was never quite sure what caused it in the first place and I don't know what the repro steps looked like. It's hard for me to say it's fixed because of that. That being said, I haven't run into it again, and if you did something that supposedly fixed it, I'll mark the issue as closed and just open a new one if I run into it again :)
