### ISSUE TITLE
Tells sending but not appearing in XIM window or in-game chat

### ISSUE THREAD

**Issue by Eg-gi** [NightmareXIV/XIVInstantMessenger#53]
I'm not sure what causes it but fairly often a message I send will just not appear in the chat history for the plugin or in-game chat. The size of the message doesn't appea to matter much because it happens to short and long messages, though I think it happens more often on longer messages. The recipient still receives the message, I just can't see it on my end.

**Comment by Limiana** [comment]
Hello! Do you use any other chat-related plugins?

**Comment by Eg-gi** [comment]
I do, specifically Chat 2. Not sure if a setting might be causing conflicts between the two.

**Comment by Limiana** [comment]
There shouldn't be any. I'll do some tests to verify it

**Comment by Eg-gi** [comment]
oh I nearly forgot I also use NoSoliciting

**Comment by Limiana** [comment]
@Eg-gi I could not confirm this issue so far. Can you send me your `dalamud.log` please?

**Comment by Limiana** [comment]
I just wanted to go through your installed plugin list and see if I could find any that can possibly interfere

**Comment by Eg-gi** [comment]
After deleting a couple of custom repositories I believe the issue was related to an outdated mod/repo. I haven't experienced the issue since. Sorry for any trouble/inconvenience!
