### ISSUE TITLE
Feature Request if possible: Input field to define the log directory

### ISSUE THREAD

**Issue by Delta87** [NightmareXIV/XIVInstantMessenger#9]
Hello!

I like your plugin really and appreciate your work.

Could it be possible so that you add an input field to define where the logs will be stored? 
its a little bit heavy if all will be saved in the dalamud directory and the ssd will be blowed up if you have many chats.. (my log dir is up to   2 gb now and i have only an 128gb ssd on my main drive.. )

best regards

**Comment by Limiana** [comment]
Added in upcoming version
